In [1]:
import pandas as pd

import numpy as np
pd.set_option('display.max_columns', None)
import mysql.connector as conn
from selenium import webdriver
import time
import re

In [2]:
from selenium import webdriver

from webdriver_manager.chrome import ChromeDriverManager

import time

In [ ]:
##Â Scrapping

In [ ]:
url='https://www.espn.com/soccer/team/squad/_/id/102/villarreal'

PATH= ChromeDriverManager().install()

driver=webdriver.Chrome(PATH)

driver.get(url)

time.sleep(3) 

# acepta cookies

aceptar=driver.find_element_by_xpath('//*[@id="onetrust-accept-btn-handler"]') 
aceptar.click()

time.sleep(3) 

#cabeceras players

cabeceras1 = driver.find_elements_by_tag_name('thead')
cabeceras1 = [c.text for c in cabeceras1]
cabeceras = cabeceras1[1]
cabeceras = cabeceras.split(" ")

# filas tabla players

tabla=driver.find_element_by_xpath('//*[@id="fittPageContainer"]/div[2]/div[5]/div/div/section/div/section/div[4]/div[2]/div[2]')

filas=tabla.find_elements_by_tag_name('tr')

datos=[[e.text for e in f.find_elements_by_tag_name('td')] for f in filas]


driver.quit()

In [ ]:
pd.DataFrame(datos, columns=cabeceras)

In [ ]:
cabeceras

In [ ]:
datos

# STOP

In [ ]:
urls =  ['https://www.espn.com/soccer/team/squad/_/id/96/alaves','https://www.espn.com/soccer/team/squad/_/id/93/athletic-bilbao','https://www.espn.com/soccer/team/squad/_/id/1068/atletico-madrid','https://www.espn.com/soccer/team/squad/_/id/83/barcelona','https://www.espn.com/soccer/team/squad/_/id/85/celta-vigo','https://www.espn.com/soccer/team/squad/_/id/3842/cadiz','https://www.espn.com/soccer/team/squad/_/id/3752/eibar','https://www.espn.com/soccer/team/squad/_/id/3751/elche','https://www.espn.com/soccer/team/squad/_/id/2922/getafe','https://www.espn.com/soccer/team/squad/_/id/3747/granada','https://www.espn.com/soccer/team/squad/_/id/5413/huesca','https://www.espn.com/soccer/team/squad/_/id/1538/levante','https://www.espn.com/soccer/team/squad/_/id/97/osasuna','https://www.espn.com/soccer/team/squad/_/id/244/real-betis','https://www.espn.com/soccer/team/squad/_/id/86/real-madrid','https://www.espn.com/soccer/team/squad/_/id/89/real-sociedad','https://www.espn.com/soccer/team/squad/_/id/95/real-valladolid','https://www.espn.com/soccer/team/squad/_/id/243/sevilla-fc','https://www.espn.com/soccer/team/squad/_/id/94/valencia','https://www.espn.com/soccer/team/squad/_/id/102/villarreal']

In [ ]:
def tablas (url):
    
    full_data = pd.DataFrame(columns = ['NAME',
 'POS',
 'AGE',
 'HT',
 'WT',
 'NAT',
 'APP',
 'SUB',
 'G',
 'A',
 'SH',
 'ST',
 'FC',
 'FA',
 'YC',
 'RC',"team"])
    
    for i in url:
        
        
        PATH= ChromeDriverManager().install()
        driver=webdriver.Chrome(PATH)
        driver.get(i)
        
        time.sleep(7) 

        # acepta cookies

        aceptar=driver.find_element_by_xpath('//*[@id="onetrust-accept-btn-handler"]') 
        aceptar.click()

        time.sleep(7) 

        #cabeceras players

        cabeceras1 = driver.find_elements_by_tag_name('thead')
        cabeceras1 = [c.text for c in cabeceras1]
        cabeceras = cabeceras1[1]
        cabeceras = cabeceras.split(" ")
        
        time.sleep(7)

        # filas tabla players

        tabla=driver.find_element_by_xpath('//*[@id="fittPageContainer"]/div[2]/div[5]/div/div/section/div/section/div[4]/div[2]/div[2]')

        filas=tabla.find_elements_by_tag_name('tr')

        datos=[[e.text for e in f.find_elements_by_tag_name('td')] for f in filas]
        
        time.sleep(7)
        
        driver.quit()
        
        time.sleep(2)
        
        df = pd.DataFrame(datos, columns=cabeceras) #append en pandas
        
        df["team"] = i.split('/')[-1]
        
        full_data = pd.concat([full_data, df])
        
        print (full_data)
        
    return full_data

In [ ]:
full_data = tablas (urls)

In [ ]:
full_data.to_csv('football_data', index=False)

## Scrappeo terminado

In [3]:
df = pd.read_csv('football_data')

In [4]:
df.columns = ['name','position','age','height','weight','nationality','appearances','substitute_sppearances','total_goals','assists','shots','shots_on_target','fouls_committed','fouls_suffered','yellow_cards','red_cards','team']

In [5]:
df.shape

(607, 17)

In [6]:
df2 = df.copy().dropna()

In [7]:
df2.columns

Index(['name', 'position', 'age', 'height', 'weight', 'nationality',
       'appearances', 'substitute_sppearances', 'total_goals', 'assists',
       'shots', 'shots_on_target', 'fouls_committed', 'fouls_suffered',
       'yellow_cards', 'red_cards', 'team'],
      dtype='object')

In [8]:
columns_reem = ['height', 'weight', 'appearances', 'substitute_sppearances', 'total_goals', 'assists',
       'shots', 'shots_on_target', 'fouls_committed', 'fouls_suffered',
       'yellow_cards', 'red_cards']

In [9]:
df2

,name,position,age,height,weight,nationality,appearances,substitute_sppearances,total_goals,assists,shots,shots_on_target,fouls_committed,fouls_suffered,yellow_cards,red_cards,team
1,Alberto RodrÃ­guez2,D,23.0,"6' 0""",159 lbs,Spain,11,4,0,0,2,0,10,16,3,1,alaves
2,RubÃ©n Duarte3,D,25.0,"5' 11""",163 lbs,Spain,30,2,1,1,14,2,41,38,5,1,alaves
3,Rodrigo Ely4,D,27.0,"6' 2""",183 lbs,Brazil,8,2,1,0,4,2,8,2,1,0,alaves
4,VÃ­ctor Laguardia5,D,31.0,"6' 1""",174 lbs,Spain,32,2,0,1,8,3,25,12,4,1,alaves
5,MartÃ­n Aguirregabiria21,D,25.0,"5' 10""",150 lbs,Spain,26,10,0,1,2,0,23,23,1,0,alaves
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,Raba 12,F,25.0,"6' 0""",168 lbs,Spain,4,3,0,0,5,1,3,7,0,0,villarreal
603,Paco AlcÃ¡cer17,F,27.0,"5' 9""",157 lbs,Spain,26,7,6,4,37,19,6,8,0,0,villarreal
604,Yeremi Pino30,F,18.0,"5' 8""",--,Spain,23,18,2,1,10,4,19,14,4,0,villarreal
605,Fernando NiÃ±o34,F,20.0,--,--,Spain,17,9,3,0,14,7,6,14,1,0,villarreal
606,Ãlex MillÃ¡n40,F,21.0,--,--,Spain,1,1,0,0,0,0,1,0,0,0,villarreal

In [10]:
df2['height'] = df2['height'].replace(['--'], '0')

df2['weight'] = df2['weight'].replace(['--'], '0')

df2['appearances'] = df2['appearances'].replace(['--'], '-1')

df2['substitute_sppearances'] = df2['substitute_sppearances'].replace(['--'], '-1')

df2['total_goals'] = df2['total_goals'].replace(['--'], '-1')

df2['assists'] = df2['assists'].replace(['--'], '-1')

df2['shots'] = df2['shots'].replace(['--'], '-1')

df2['shots_on_target'] = df2['shots_on_target'].replace(['--'], '-1')

df2['fouls_committed'] = df2['fouls_committed'].replace(['--'], '-1')

df2['fouls_suffered'] = df2['fouls_suffered'].replace(['--'], '-1')

df2['yellow_cards'] = df2['yellow_cards'].replace(['--'], '-1')

df2['red_cards'] = df2['red_cards'].replace(['--'], '-1')

In [11]:
df2

,name,position,age,height,weight,nationality,appearances,substitute_sppearances,total_goals,assists,shots,shots_on_target,fouls_committed,fouls_suffered,yellow_cards,red_cards,team
1,Alberto RodrÃ­guez2,D,23.0,"6' 0""",159 lbs,Spain,11,4,0,0,2,0,10,16,3,1,alaves
2,RubÃ©n Duarte3,D,25.0,"5' 11""",163 lbs,Spain,30,2,1,1,14,2,41,38,5,1,alaves
3,Rodrigo Ely4,D,27.0,"6' 2""",183 lbs,Brazil,8,2,1,0,4,2,8,2,1,0,alaves
4,VÃ­ctor Laguardia5,D,31.0,"6' 1""",174 lbs,Spain,32,2,0,1,8,3,25,12,4,1,alaves
5,MartÃ­n Aguirregabiria21,D,25.0,"5' 10""",150 lbs,Spain,26,10,0,1,2,0,23,23,1,0,alaves
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,Raba 12,F,25.0,"6' 0""",168 lbs,Spain,4,3,0,0,5,1,3,7,0,0,villarreal
603,Paco AlcÃ¡cer17,F,27.0,"5' 9""",157 lbs,Spain,26,7,6,4,37,19,6,8,0,0,villarreal
604,Yeremi Pino30,F,18.0,"5' 8""",0,Spain,23,18,2,1,10,4,19,14,4,0,villarreal
605,Fernando NiÃ±o34,F,20.0,0,0,Spain,17,9,3,0,14,7,6,14,1,0,villarreal
606,Ãlex MillÃ¡n40,F,21.0,0,0,Spain,1,1,0,0,0,0,1,0,0,0,villarreal

In [12]:
df2[['age', 'appearances','substitute_sppearances','total_goals','assists','shots','shots_on_target','fouls_committed','fouls_suffered','yellow_cards','red_cards']]= df2[['age', 'appearances','substitute_sppearances','total_goals','assists','shots','shots_on_target','fouls_committed','fouls_suffered','yellow_cards','red_cards']].astype(int)

In [13]:
df2

,name,position,age,height,weight,nationality,appearances,substitute_sppearances,total_goals,assists,shots,shots_on_target,fouls_committed,fouls_suffered,yellow_cards,red_cards,team
1,Alberto RodrÃ­guez2,D,23,"6' 0""",159 lbs,Spain,11,4,0,0,2,0,10,16,3,1,alaves
2,RubÃ©n Duarte3,D,25,"5' 11""",163 lbs,Spain,30,2,1,1,14,2,41,38,5,1,alaves
3,Rodrigo Ely4,D,27,"6' 2""",183 lbs,Brazil,8,2,1,0,4,2,8,2,1,0,alaves
4,VÃ­ctor Laguardia5,D,31,"6' 1""",174 lbs,Spain,32,2,0,1,8,3,25,12,4,1,alaves
5,MartÃ­n Aguirregabiria21,D,25,"5' 10""",150 lbs,Spain,26,10,0,1,2,0,23,23,1,0,alaves
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,Raba 12,F,25,"6' 0""",168 lbs,Spain,4,3,0,0,5,1,3,7,0,0,villarreal
603,Paco AlcÃ¡cer17,F,27,"5' 9""",157 lbs,Spain,26,7,6,4,37,19,6,8,0,0,villarreal
604,Yeremi Pino30,F,18,"5' 8""",0,Spain,23,18,2,1,10,4,19,14,4,0,villarreal
605,Fernando NiÃ±o34,F,20,0,0,Spain,17,9,3,0,14,7,6,14,1,0,villarreal
606,Ãlex MillÃ¡n40,F,21,0,0,Spain,1,1,0,0,0,0,1,0,0,0,villarreal

In [14]:
df2['height'] = df2['height'].replace(['5\' 10"'], '1,55')
df2['height'] = df2['height'].replace(['5\' 11"'], '1,55')
df2['height'] = df2['height'].replace(['5\' 4"'], '1,64')
df2['height'] = df2['height'].replace(['5\' 5"'], '1,67')
df2['height'] = df2['height'].replace(['5\' 6"'], '1,70')
df2['height'] = df2['height'].replace(['5\' 7"'], '1,73')
df2['height'] = df2['height'].replace(['5\' 8"'], '1,76')
df2['height'] = df2['height'].replace(['5\' 9"'], '1,79')
df2['height'] = df2['height'].replace(['6\' 0"'], '1,82')
df2['height'] = df2['height'].replace(['6\' 1"'], '1,85')
df2['height'] = df2['height'].replace(['6\' 2"'], '1,88')
df2['height'] = df2['height'].replace(['6\' 3"'], '1,92')
df2['height'] = df2['height'].replace(['6\' 4"'], '1,95')
df2['height'] = df2['height'].replace(['6\' 5"'], '2')

In [15]:
df2

,name,position,age,height,weight,nationality,appearances,substitute_sppearances,total_goals,assists,shots,shots_on_target,fouls_committed,fouls_suffered,yellow_cards,red_cards,team
1,Alberto RodrÃ­guez2,D,23,"1,82",159 lbs,Spain,11,4,0,0,2,0,10,16,3,1,alaves
2,RubÃ©n Duarte3,D,25,"1,55",163 lbs,Spain,30,2,1,1,14,2,41,38,5,1,alaves
3,Rodrigo Ely4,D,27,"1,88",183 lbs,Brazil,8,2,1,0,4,2,8,2,1,0,alaves
4,VÃ­ctor Laguardia5,D,31,"1,85",174 lbs,Spain,32,2,0,1,8,3,25,12,4,1,alaves
5,MartÃ­n Aguirregabiria21,D,25,"1,55",150 lbs,Spain,26,10,0,1,2,0,23,23,1,0,alaves
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,Raba 12,F,25,"1,82",168 lbs,Spain,4,3,0,0,5,1,3,7,0,0,villarreal
603,Paco AlcÃ¡cer17,F,27,"1,79",157 lbs,Spain,26,7,6,4,37,19,6,8,0,0,villarreal
604,Yeremi Pino30,F,18,"1,76",0,Spain,23,18,2,1,10,4,19,14,4,0,villarreal
605,Fernando NiÃ±o34,F,20,0,0,Spain,17,9,3,0,14,7,6,14,1,0,villarreal
606,Ãlex MillÃ¡n40,F,21,0,0,Spain,1,1,0,0,0,0,1,0,0,0,villarreal

In [16]:
df2['weight'] = df2['weight'].apply(lambda x : x.replace(' lbs',''))

In [17]:
df2['weight']= df2[['weight']].astype(float)

In [18]:
df2['weight'] = df2['weight'] * 0.45

In [19]:
df2['weight']

1      71.55
2      73.35
3      82.35
4      78.30
5      67.50
       ...
602    75.60
603    70.65
604     0.00
605     0.00
606     0.00
Name: weight, Length: 587, dtype: float64

In [20]:
separado = []

for i in df2.name:
    
    separado.append(re.split('(\d+)',i))

print(separado[:5])

[['Alberto RodrÃ­guez', '2', ''], ['RubÃ©n Duarte', '3', ''], ['Rodrigo Ely', '4', ''], ['VÃ­ctor Laguardia', '5', ''], ['MartÃ­n Aguirregabiria', '21', '']]

In [21]:
separado[:4]

[['Alberto RodrÃ­guez', '2', ''],
 ['RubÃ©n Duarte', '3', ''],
 ['Rodrigo Ely', '4', ''],
 ['VÃ­ctor Laguardia', '5', '']]

In [22]:
nombres = []
for i in separado:
    nombres.append(i[0])

In [23]:
print(nombres[:10])

['Alberto RodrÃ­guez', 'RubÃ©n Duarte', 'Rodrigo Ely', 'VÃ­ctor Laguardia', 'MartÃ­n Aguirregabiria', 'Florian Lejeune', 'Ximo Navarro', 'Javier LÃ³pez', 'Abdelkabir Abqar', 'Hugo PÃ©rez']

In [24]:
dorsal = []
for i in separado:
    try:
        dorsal.append(i[1])
    except:
        dorsal.append(0)

In [25]:
dorsal[5]

'22'

In [26]:
df2.name = nombres

df2['dorsal'] = dorsal

In [27]:
df2.columns

Index(['name', 'position', 'age', 'height', 'weight', 'nationality',
       'appearances', 'substitute_sppearances', 'total_goals', 'assists',
       'shots', 'shots_on_target', 'fouls_committed', 'fouls_suffered',
       'yellow_cards', 'red_cards', 'team', 'dorsal'],
      dtype='object')

In [28]:
df2 = df2.reindex(columns=['name','dorsal','team', 'position', 'age', 'height', 'weight', 'nationality',
       'appearances', 'substitute_sppearances', 'total_goals', 'assists',
       'shots', 'shots_on_target', 'fouls_committed', 'fouls_suffered',
       'yellow_cards', 'red_cards'])

In [29]:
df2['ratio_goalshots'] = df2.total_goals / df2.shots_on_target

In [30]:
df2.ratio_goalshots

1           NaN
2      0.500000
3      0.500000
4      0.000000
5           NaN
         ...
602    0.000000
603    0.315789
604    0.500000
605    0.428571
606         NaN
Name: ratio_goalshots, Length: 587, dtype: float64

In [31]:
df2.ratio_goalshots = df2.ratio_goalshots.fillna(0)

In [32]:
df2.columns

Index(['name', 'dorsal', 'team', 'position', 'age', 'height', 'weight',
       'nationality', 'appearances', 'substitute_sppearances', 'total_goals',
       'assists', 'shots', 'shots_on_target', 'fouls_committed',
       'fouls_suffered', 'yellow_cards', 'red_cards', 'ratio_goalshots'],
      dtype='object')

In [33]:
df2['ratio_assists_appearances'] = df2.assists / df2.appearances

df2['ratio_total_goalss_appearances'] = df2.total_goals / df2.appearances

In [34]:
df2['ratio_total_fouls_committed_appearances'] = df2.fouls_committed / df2.appearances

df2['ratio_total_fouls_suffered_appearances'] = df2.fouls_suffered / df2.appearances

df2['ratio_total_yellow_cards_appearances'] = df2.yellow_cards / df2.appearances

df2['ratio_total_red_cards_appearances'] = df2.red_cards / df2.appearances

In [35]:
df2

,name,dorsal,team,position,age,height,weight,nationality,appearances,substitute_sppearances,total_goals,assists,shots,shots_on_target,fouls_committed,fouls_suffered,yellow_cards,red_cards,ratio_goalshots,ratio_assists_appearances,ratio_total_goalss_appearances,ratio_total_fouls_committed_appearances,ratio_total_fouls_suffered_appearances,ratio_total_yellow_cards_appearances,ratio_total_red_cards_appearances
1,Alberto RodrÃ­guez,2,alaves,D,23,"1,82",71.55,Spain,11,4,0,0,2,0,10,16,3,1,0.000000,0.000000,0.000000,0.909091,1.454545,0.272727,0.090909
2,RubÃ©n Duarte,3,alaves,D,25,"1,55",73.35,Spain,30,2,1,1,14,2,41,38,5,1,0.500000,0.033333,0.033333,1.366667,1.266667,0.166667,0.033333
3,Rodrigo Ely,4,alaves,D,27,"1,88",82.35,Brazil,8,2,1,0,4,2,8,2,1,0,0.500000,0.000000,0.125000,1.000000,0.250000,0.125000,0.000000
4,VÃ­ctor Laguardia,5,alaves,D,31,"1,85",78.30,Spain,32,2,0,1,8,3,25,12,4,1,0.000000,0.031250,0.000000,0.781250,0.375000,0.125000,0.031250
5,MartÃ­n Aguirregabiria,21,alaves,D,25,"1,55",67.50,Spain,26,10,0,1,2,0,23,23,1,0,0.000000,0.038462,0.000000,0.884615,0.884615,0.038462,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,Raba,12,villarreal,F,25,"1,82",75.60,Spain,4,3,0,0,5,1,3,7,0,0,0.000000,0.000000,0.000000,0.750000,1.750000,0.000000,0.000000
603,Paco AlcÃ¡cer,17,villarreal,F,27,"1,79",70.65,Spain,26,7,6,4,37,19,6,8,0,0,0.315789,0.153846,0.230769,0.230769,0.307692,0.000000,0.000000
604,Yeremi Pino,30,villarreal,F,18,"1,76",0.00,Spain,23,18,2,1,10,4,19,14,4,0,0.500000,0.043478,0.086957,0.826087,0.608696,0.173913,0.000000
605,Fernando NiÃ±o,34,villarreal,F,20,0,0.00,Spain,17,9,3,0,14,7,6,14,1,0,0.428571,0.000000,0.176471,0.352941,0.823529,0.058824,0.000000
606,Ãlex MillÃ¡n,40,villarreal,F,21,0,0.00,Spain,1,1,0,0,0,0,1,0,0,0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000

In [36]:
df2.to_csv('Finalizado_Football.csv', index = False)

In [37]:
df2

,name,dorsal,team,position,age,height,weight,nationality,appearances,substitute_sppearances,total_goals,assists,shots,shots_on_target,fouls_committed,fouls_suffered,yellow_cards,red_cards,ratio_goalshots,ratio_assists_appearances,ratio_total_goalss_appearances,ratio_total_fouls_committed_appearances,ratio_total_fouls_suffered_appearances,ratio_total_yellow_cards_appearances,ratio_total_red_cards_appearances
1,Alberto RodrÃ­guez,2,alaves,D,23,"1,82",71.55,Spain,11,4,0,0,2,0,10,16,3,1,0.000000,0.000000,0.000000,0.909091,1.454545,0.272727,0.090909
2,RubÃ©n Duarte,3,alaves,D,25,"1,55",73.35,Spain,30,2,1,1,14,2,41,38,5,1,0.500000,0.033333,0.033333,1.366667,1.266667,0.166667,0.033333
3,Rodrigo Ely,4,alaves,D,27,"1,88",82.35,Brazil,8,2,1,0,4,2,8,2,1,0,0.500000,0.000000,0.125000,1.000000,0.250000,0.125000,0.000000
4,VÃ­ctor Laguardia,5,alaves,D,31,"1,85",78.30,Spain,32,2,0,1,8,3,25,12,4,1,0.000000,0.031250,0.000000,0.781250,0.375000,0.125000,0.031250
5,MartÃ­n Aguirregabiria,21,alaves,D,25,"1,55",67.50,Spain,26,10,0,1,2,0,23,23,1,0,0.000000,0.038462,0.000000,0.884615,0.884615,0.038462,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,Raba,12,villarreal,F,25,"1,82",75.60,Spain,4,3,0,0,5,1,3,7,0,0,0.000000,0.000000,0.000000,0.750000,1.750000,0.000000,0.000000
603,Paco AlcÃ¡cer,17,villarreal,F,27,"1,79",70.65,Spain,26,7,6,4,37,19,6,8,0,0,0.315789,0.153846,0.230769,0.230769,0.307692,0.000000,0.000000
604,Yeremi Pino,30,villarreal,F,18,"1,76",0.00,Spain,23,18,2,1,10,4,19,14,4,0,0.500000,0.043478,0.086957,0.826087,0.608696,0.173913,0.000000
605,Fernando NiÃ±o,34,villarreal,F,20,0,0.00,Spain,17,9,3,0,14,7,6,14,1,0,0.428571,0.000000,0.176471,0.352941,0.823529,0.058824,0.000000
606,Ãlex MillÃ¡n,40,villarreal,F,21,0,0.00,Spain,1,1,0,0,0,0,1,0,0,0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000